apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pulls-service-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pulls-service
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80